const menuList = [
    {
      hotelName: "Mughal Hotel",
      menu: {
        starters: [
          { name: "Paneer Butter Masala", price: 240, isVeg: true },
          { name: "Chicken Tikka", price: 320, isVeg: false },
          { name: "Veg Spring Rolls", price: 200, isVeg: true },
          { name: "Mutton Seekh Kebab", price: 400, isVeg: false },
          { name: "Hara Bhara Kebab", price: 220, isVeg: true },
          { name: "Fish Amritsari", price: 380, isVeg: false },
        ],
        mainCourse: [
          { name: "Butter Chicken", price: 360, isVeg: false },
          { name: "Dal Makhani", price: 180, isVeg: true },
          { name: "Shahi Paneer", price: 240, isVeg: true },
          { name: "Rogan Josh", price: 420, isVeg: false },
          { name: "Malai Kofta", price: 250, isVeg: true },
          { name: "Chicken Curry", price: 340, isVeg: false },
        ],
        gravies: [
          { name: "Paneer Tikka Masala", price: 250, isVeg: true },
          { name: "Kadhai Chicken", price: 350, isVeg: false },
          { name: "Palak Paneer", price: 220, isVeg: true },
          { name: "Fish Curry", price: 370, isVeg: false },
          { name: "Mushroom Masala", price: 200, isVeg: true },
          { name: "Prawn Masala", price: 450, isVeg: false },
        ],
        bread: [
          { name: "Butter Naan", price: 50, isVeg: true },
          { name: "Garlic Naan", price: 60, isVeg: true },
          { name: "Tandoori Roti", price: 40, isVeg: true },
          { name: "Laccha Paratha", price: 70, isVeg: true },
          { name: "Missi Roti", price: 50, isVeg: true },
          { name: "Stuffed Kulcha", price: 80, isVeg: true },
        ],
        desserts: [
          { name: "Gulab Jamun", price: 120, isVeg: true },
          { name: "Rasmalai", price: 150, isVeg: true },
          { name: "Ice Cream Sundae", price: 200, isVeg: true },
          { name: "Chocolate Brownie", price: 180, isVeg: true },
          { name: "Kheer", price: 140, isVeg: true },
          { name: "Jalebi with Rabri", price: 200, isVeg: true },
        ],
      },
    },
    {
      hotelName: "Spice Symphony",
      menu: {
        starters: [
          { name: "Veg Manchurian", price: 210, isVeg: true },
          { name: "Chicken Lollipop", price: 330, isVeg: false },
          { name: "Paneer Tikka", price: 260, isVeg: true },
          { name: "Fish Fingers", price: 380, isVeg: false },
          { name: "Crispy Corn", price: 190, isVeg: true },
          { name: "Mutton Chops", price: 450, isVeg: false },
        ],
        mainCourse: [
          { name: "Paneer Butter Masala", price: 240, isVeg: true },
          { name: "Chicken Biryani", price: 350, isVeg: false },
          { name: "Veg Fried Rice", price: 180, isVeg: true },
          { name: "Hyderabadi Mutton Curry", price: 500, isVeg: false },
          { name: "Aloo Gobi Masala", price: 180, isVeg: true },
          { name: "Egg Curry", price: 220, isVeg: false },
        ],
        gravies: [
          { name: "Paneer Lababdar", price: 260, isVeg: true },
          { name: "Butter Chicken", price: 360, isVeg: false },
          { name: "Mix Vegetable Curry", price: 190, isVeg: true },
          { name: "Fish Moilee", price: 420, isVeg: false },
          { name: "Dum Aloo", price: 200, isVeg: true },
          { name: "Prawn Curry", price: 450, isVeg: false },
        ],
        bread: [
          { name: "Plain Naan", price: 40, isVeg: true },
          { name: "Butter Naan", price: 50, isVeg: true },
          { name: "Tandoori Roti", price: 40, isVeg: true },
          { name: "Cheese Naan", price: 80, isVeg: true },
          { name: "Stuffed Paratha", price: 70, isVeg: true },
          { name: "Romali Roti", price: 60, isVeg: true },
        ],
        desserts: [
          { name: "Shahi Tukda", price: 180, isVeg: true },
          { name: "Mango Kulfi", price: 150, isVeg: true },
          { name: "Chocolate Mousse", price: 220, isVeg: true },
          { name: "Rasgulla", price: 120, isVeg: true },
          { name: "Phirni", price: 160, isVeg: true },
          { name: "Gajar Ka Halwa", price: 200, isVeg: true },
        ],
      },
    },
    {
      hotelName: "Ocean Breeze",
      menu: {
        starters: [
          { name: "Veg Hakka Noodles", price: 220, isVeg: true },
          { name: "Chicken Wings", price: 340, isVeg: false },
          { name: "Stuffed Mushrooms", price: 250, isVeg: true },
          { name: "Fish Pakora", price: 400, isVeg: false },
          { name: "Samosa Chaat", price: 160, isVeg: true },
          { name: "Chicken Satay", price: 450, isVeg: false },
        ],
        mainCourse: [
          { name: "Paneer Do Pyaza", price: 240, isVeg: true },
          { name: "Mutton Biryani", price: 420, isVeg: false },
          { name: "Veg Pulao", price: 180, isVeg: true },
          { name: "Chicken Korma", price: 360, isVeg: false },
          { name: "Bhindi Masala", price: 190, isVeg: true },
          { name: "Egg Fried Rice", price: 220, isVeg: false },
        ],
        gravies: [
          { name: "Paneer Bhurji", price: 220, isVeg: true },
          { name: "Chicken Handi", price: 380, isVeg: false },
          { name: "Rajma Curry", price: 180, isVeg: true },
          { name: "Fish Malabar Curry", price: 450, isVeg: false },
          { name: "Aloo Dum", price: 190, isVeg: true },
          { name: "Prawn Vindaloo", price: 500, isVeg: false },
        ],
        bread: [
          { name: "Plain Paratha", price: 50, isVeg: true },
          { name: "Butter Roti", price: 40, isVeg: true },
          { name: "Garlic Bread", price: 90, isVeg: true },
          { name: "Stuffed Kulcha", price: 80, isVeg: true },
          { name: "Makki Ki Roti", price: 70, isVeg: true },
          { name: "Tandoori Naan", price: 60, isVeg: true },
        ],
        desserts: [
          { name: "Lassi", price: 100, isVeg: true },
          { name: "Ice Cream", price: 180, isVeg: true },
          { name: "Jalebi", price: 120, isVeg: true },
          { name: "Cheesecake", price: 250, isVeg: true },
          { name: "Kaju Katli", price: 200, isVeg: true },
          { name: "Custard", price: 160, isVeg: true },
        ],
      },
    },
    {      
    hotelName: "Cafe Wildbeans",
      menu: {
        starters: [
          { name: "Paneer Butter Masala", price: 240, isVeg: true },
          { name: "Chicken Tikka", price: 320, isVeg: false },
          { name: "Veg Spring Rolls", price: 200, isVeg: true },
          { name: "Mutton Seekh Kebab", price: 400, isVeg: false },
          { name: "Hara Bhara Kebab", price: 220, isVeg: true },
          { name: "Fish Amritsari", price: 380, isVeg: false },
        ],
        mainCourse: [
          { name: "Butter Chicken", price: 360, isVeg: false },
          { name: "Dal Makhani", price: 180, isVeg: true },
          { name: "Shahi Paneer", price: 240, isVeg: true },
          { name: "Rogan Josh", price: 420, isVeg: false },
          { name: "Malai Kofta", price: 250, isVeg: true },
          { name: "Chicken Curry", price: 340, isVeg: false },
        ],
        gravies: [
          { name: "Paneer Tikka Masala", price: 250, isVeg: true },
          { name: "Kadhai Chicken", price: 350, isVeg: false },
          { name: "Palak Paneer", price: 220, isVeg: true },
          { name: "Fish Curry", price: 370, isVeg: false },
          { name: "Mushroom Masala", price: 200, isVeg: true },
          { name: "Prawn Masala", price: 450, isVeg: false },
        ],
        bread: [
          { name: "Butter Naan", price: 50, isVeg: true },
          { name: "Garlic Naan", price: 60, isVeg: true },
          { name: "Tandoori Roti", price: 40, isVeg: true },
          { name: "Laccha Paratha", price: 70, isVeg: true },
          { name: "Missi Roti", price: 50, isVeg: true },
          { name: "Stuffed Kulcha", price: 80, isVeg: true },
        ],
        desserts: [
          { name: "Gulab Jamun", price: 120, isVeg: true },
          { name: "Rasmalai", price: 150, isVeg: true },
          { name: "Ice Cream Sundae", price: 200, isVeg: true },
          { name: "Chocolate Brownie", price: 180, isVeg: true },
          { name: "Kheer", price: 140, isVeg: true },
          { name: "Jalebi with Rabri", price: 200, isVeg: true },
        ],
      },
    },
    {
      hotelName: "Skyline Diner",
      menu: {
        starters: [
          { name: "Veg Manchurian", price: 210, isVeg: true },
          { name: "Chicken Lollipop", price: 330, isVeg: false },
          { name: "Paneer Tikka", price: 260, isVeg: true },
          { name: "Fish Fingers", price: 380, isVeg: false },
          { name: "Crispy Corn", price: 190, isVeg: true },
          { name: "Mutton Chops", price: 450, isVeg: false },
        ],
        mainCourse: [
          { name: "Paneer Butter Masala", price: 240, isVeg: true },
          { name: "Chicken Biryani", price: 350, isVeg: false },
          { name: "Veg Fried Rice", price: 180, isVeg: true },
          { name: "Hyderabadi Mutton Curry", price: 500, isVeg: false },
          { name: "Aloo Gobi Masala", price: 180, isVeg: true },
          { name: "Egg Curry", price: 220, isVeg: false },
        ],
        gravies: [
          { name: "Paneer Lababdar", price: 260, isVeg: true },
          { name: "Butter Chicken", price: 360, isVeg: false },
          { name: "Mix Vegetable Curry", price: 190, isVeg: true },
          { name: "Fish Moilee", price: 420, isVeg: false },
          { name: "Dum Aloo", price: 200, isVeg: true },
          { name: "Prawn Curry", price: 450, isVeg: false },
        ],
        bread: [
          { name: "Plain Naan", price: 40, isVeg: true },
          { name: "Butter Naan", price: 50, isVeg: true },
          { name: "Tandoori Roti", price: 40, isVeg: true },
          { name: "Cheese Naan", price: 80, isVeg: true },
          { name: "Stuffed Paratha", price: 70, isVeg: true },
          { name: "Romali Roti", price: 60, isVeg: true },
        ],
        desserts: [
          { name: "Shahi Tukda", price: 180, isVeg: true },
          { name: "Mango Kulfi", price: 150, isVeg: true },
          { name: "Chocolate Mousse", price: 220, isVeg: true },
          { name: "Rasgulla", price: 120, isVeg: true },
          { name: "Phirni", price: 160, isVeg: true },
          { name: "Gajar Ka Halwa", price: 200, isVeg: true },
        ],
      },
    },
    {
      hotelName: "Mountain Retreat",
      menu: {
        starters: [
          { name: "Veg Hakka Noodles", price: 220, isVeg: true },
          { name: "Chicken Wings", price: 340, isVeg: false },
          { name: "Stuffed Mushrooms", price: 250, isVeg: true },
          { name: "Fish Pakora", price: 400, isVeg: false },
          { name: "Samosa Chaat", price: 160, isVeg: true },
          { name: "Chicken Satay", price: 450, isVeg: false },
        ],
        mainCourse: [
          { name: "Paneer Do Pyaza", price: 240, isVeg: true },
          { name: "Mutton Biryani", price: 420, isVeg: false },
          { name: "Veg Pulao", price: 180, isVeg: true },
          { name: "Chicken Korma", price: 360, isVeg: false },
          { name: "Bhindi Masala", price: 190, isVeg: true },
          { name: "Egg Fried Rice", price: 220, isVeg: false },
        ],
        gravies: [
          { name: "Paneer Bhurji", price: 220, isVeg: true },
          { name: "Chicken Handi", price: 380, isVeg: false },
          { name: "Rajma Curry", price: 180, isVeg: true },
          { name: "Fish Malabar Curry", price: 450, isVeg: false },
          { name: "Aloo Dum", price: 190, isVeg: true },
          { name: "Prawn Vindaloo", price: 500, isVeg: false },
        ],
        bread: [
          { name: "Plain Paratha", price: 50, isVeg: true },
          { name: "Butter Roti", price: 40, isVeg: true },
          { name: "Garlic Bread", price: 90, isVeg: true },
          { name: "Stuffed Kulcha", price: 80, isVeg: true },
          { name: "Makki Ki Roti", price: 70, isVeg: true },
          { name: "Tandoori Naan", price: 60, isVeg: true },
        ],
        desserts: [
          { name: "Lassi", price: 100, isVeg: true },
          { name: "Ice Cream", price: 180, isVeg: true },
          { name: "Jalebi", price: 120, isVeg: true },
          { name: "Cheesecake", price: 250, isVeg: true },
          { name: "Kaju Katli", price: 200, isVeg: true },
          { name: "Custard", price: 160, isVeg: true },
        ],
      },
    },
  ];
  
export default menuList;